### ISSUE TITLE
Program sometimes crashes when clicking Soundcloud button

### ISSUE THREAD

**Issue by metoxys** [flairmax/FlairMax-Issues#1]
Clicked it 3 times so far  
One time, it opened the track on Soundcloud in my browser in a new tab; the other two times, the program crashed

**Comment by ahmed605** [comment]
Does the crash happen on particular tracks or it's random?

**Comment by metoxys** [comment]
I guess particular tracks. I tried around a bit, and if it works for one tune, it will work consistently (like, if I press it again a few times for the same track)

**Comment by ahmed605** [comment]
I see, will take a look at it as soon as I can, thanks for reporting the issue

**Comment by metoxys** [comment]
Just crashed on Lovell - Nothing To Ya  
Before that, I accidentally pressed the Apple Music link and that worked fine

**Comment by metoxys** [comment]
Unrelated question, should I also use this issue board for feature suggestions/requests? Started using this program a few hours ago and loving it so far, but I'm already seeing some simple quality of life improvements that can be added

**Comment by ahmed605** [comment]
> Unrelated question, should I also use this issue board for feature suggestions/requests? Started using this program a few hours ago and loving it so far, but I'm already seeing some simple quality of life improvements that can be added

Yes!
The app accepts feature requests and suggestions too, but please open separate issues for each suggestion/feature request

**Comment by ahmed605** [comment]
I fixed the issue locally, it will be included in the next update so I'll leave the issue open until the next update  gets released.
Thanks for reporting it!

**Comment by ahmed605** [comment]
fixed as of v1.1.2
