### ISSUE TITLE
(Feature request) Add button to copy artist & title together

### ISSUE THREAD

**Issue by metoxys** [flairmax/FlairMax-Issues#2]
![image](https://user-images.githubusercontent.com/6764458/230799475-d8a428c5-14c9-4ff2-9a34-e3ae2c99ee1d.png)
I guess in this dropdown menu you select what you want to share/copy to clipboard.  
I'd love to see an option for artist + title, in the format `artist - title`, like `Michael Jackson - Billie Jean`

**Comment by ahmed605** [comment]
Good suggestion, should it also be the default option? I think it makes sense for it to be the default option

**Comment by metoxys** [comment]
> I think it makes sense for it to be the default option  

Agree

**Comment by ahmed605** [comment]
fixed as of v1.1.2
