### ISSUE TITLE
FlairMax seems to struggle with drag & dropped .mp3 files

### ISSUE THREAD

**Issue by metoxys** [flairmax/FlairMax-Issues#3]
![image](https://user-images.githubusercontent.com/6764458/230924059-d079bbfd-aaf0-4bba-bfaf-0f08264b61e4.png)
Screenshot in question is with a 1:54 minutes long 48000 Hz 320 kbps stereo .mp3 file without any special characters in the filename  
I don't think FlairMax should have a problem with mp3 files!

**Comment by ahmed605** [comment]
What Core do you use?
Also it would be great if you can send me the file causing the issue
I'm pretty sure I tested every format FlairMax supports which includes mp3 format, but my guess is that this is a regression of the changes in the latest update as I dropped the library used previously to read files to use system APIs instead

**Comment by metoxys** [comment]
Using Shazam/default core

Multiple files caused the issue, I'll just upload the one that caused the screenshot  
(can't upload mp3 as attachment, so have [this wetransfer link](https://we.tl/t-1APczz57Wl) instead)

**Comment by ahmed605** [comment]
@metoxys v1.1.2 (or v1.1.102 if you are running on ARM64) includes a fix for this, can you update to it and confirm if it fixes the issue?

**Comment by metoxys** [comment]
Confirming fixed

**Comment by ahmed605** [comment]
Thanks for confirming!
